### ISSUE TITLE
schicht zuweißung drop down

### ISSUE THREAD

**Issue by BauerBank** [HaDiNet/shiftings#20]
Ich bekomme jedes mal ein Error wenn ich jemandem eine Schicht durch das neue drop down Menü zuweisen möchte. Egal ob die Schicht in der Vergangenheit liegt oder nicht.

**Comment by BauerBank** [comment]
![image](https://user-images.githubusercontent.com/94458982/234243581-0aafc499-f97e-48d7-bf9d-cbd1eb16cb7b.png)

die Schicht zusweisung funktioniert immer noch nicht leider :(

**Comment by Tjeri** [comment]
Schon länger gefixt, nur Issue nicht bearbeitet gehabt.
