### ISSUE TITLE
Organisationsoptionen

### ISSUE THREAD

**Issue by mfbehrens99** [HaDiNet/shiftings#25]
Hätte zwei Optionen die eigentlich noch ganz praktisch wären

Eine Checkbox für die Organisation "Organisationsmitglieder dürfen andere Organisationsmitglieder eintragen"
Eine Option, dass alle Mitglieder sich noch nach der Schicht eintragen können

**Comment by Tjeri** [comment]
Es gibt bereits ein Recht für andere Organisationsmitglieder eintragen. Das müsste der Admin der entsprechenden Gruppe halt setzen.
Habe eine Permission für eintragen nach Ende der Schicht eingeführt -> #28
